[package]
name = "config-site"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1"
defmt = { workspace = true, optional = true }
edge-http = { workspace = true, optional = true }
embassy-sync = { workspace = true, optional = true }
embedded-io-async = { workspace = true, optional = true }
heapless = { workspace = true }
norfs = { workspace = true, optional = true }
smol = { version = "2", optional = true }

[build-dependencies]
libflate = { version = "1.4.0", optional = true }
minify-html = { version = "0.11.1", optional = true }

[[example]]
name = "simple"
required-features = ["std", "serve", "compress"]

[dev-dependencies]
edge-nal = { workspace = true }
embassy-time = { workspace = true, features = ["std", "generic-queue-8"] }
edge-nal-std = "0.7"
smol = "2"

[features]
default = []
embedded = ["dep:norfs", "dep:embassy-sync", "dep:embedded-io-async"]
compress = ["dep:minify-html", "dep:libflate"]
serve = ["dep:edge-http", "dep:embedded-io-async"]
std = ["dep:smol", "edge-http?/std"]
defmt = ["dep:defmt", "edge-http?/defmt"]
