[esp-wifi]
rx_queue_size = 20
tx_queue_size = 5
static_rx_buf_num = 32
dynamic_rx_buf_num = 16
static_tx_buf_num = 8
dynamic_tx_buf_num = 16
ampdu_rx_enable = 1
ampdu_tx_enable = 1
rx_ba_win = 32
max_burst_size = 0 # 0 means no limit
tick_rate_hz = 200
