[package]
name = "logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defmt = { workspace = true, optional = true }
log = { workspace = true, optional = true }

[features]
log = ["dep:log"]
defmt = ["dep:defmt"]
