name: Check firmware

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: false
      - uses: Swatinem/rust-cache@v2

      - uses: cargo-bins/cargo-binstall@main
      - name: setup espflash
        run: cargo binstall --no-confirm --force cargo-espflash

      - name: format check
        run: cargo fmt --check

      - name: test
        run: cargo xtask test
  
      - name: build
        run: cargo xbuild
