name: Merge PR

on:
  merge_group:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: false
      - uses: Swatinem/rust-cache@v2

      - uses: cargo-bins/cargo-binstall@main
      - name: setup espflash
        run: cargo binstall --no-confirm --force cargo-espflash

      - name: check
        run: cargo xcheck

      - name: test
        run: cargo xtask test
  
      - name: build
        run: cargo xbuild
